### ISSUE TITLE
Align to other genes

### ISSUE THREAD

**Issue by sureman** [hivdb/nucamino#14]
Thank you for this very helpful tool.  I was wondering if there was a way to set nucamino up to align other regions such as envelope?

**Comment by nathanielknight** [comment]
In principle you can align against an arbitrary sequence, so if you have the reference that you're trying to align against, yes.

To do this, you need to compose a YAML file with the alignment parameters and reference sequences. It isn't documented in detail, but you can see examples with the `nucamino profile print` command.

**Comment by sureman** [comment]
Thank you for the quick and helpful answer.
